aliases: []
creation_timestamp: 1711469948674
current_stage: Staging
description: ''
last_updated_timestamp: 1711470569054
name: NLP_SENTIMENTAL_ANALYSIS_PROJECT
run_id: a9d34d0ffd234ba9bfb91e78b82d148a
run_link: ''
source: file:///Users/prashantheleshala/Desktop/DESKTOP/INTERNSHIP/INNOMATICS%20/ML_PROJECT/mlruns/312492107488539227/a9d34d0ffd234ba9bfb91e78b82d148a/artifacts/best_estimator
status: READY
status_message: null
storage_location: file:///Users/prashantheleshala/Desktop/DESKTOP/INTERNSHIP/INNOMATICS%20/ML_PROJECT/mlruns/312492107488539227/a9d34d0ffd234ba9bfb91e78b82d148a/artifacts/best_estimator
user_id: null
version: 2
